apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /task
        pathType: Prefix
        backend:
          service:
            name: cart
            port:
              number: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: twelve-per-min
config:
  minute: 12
  policy: local
plugin: rate-limiting

---
apiVersion: v1
kind: Service
metadata:
  name: taskitem
  annotations:
   konghq.com/plugins: twelve-per-min
spec:
  type: NodePort
  selector:
    app: taskitem
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: taskprocessitem
  annotations:
   konghq.com/plugins: twelve-per-min
spec:
  type: NodePort
  selector:
    app: taskprocessitem
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
